// Package lockfile provides types and functions for reading schemalock.yaml
// (intent) and reading/writing schemalock.lock (integrity-pinned lockfile).
//
// The intent file (schemalock.yaml) is authored by the user and declares
// which schema groups to pin. The lockfile (schemalock.lock) is generated by
// `schemalock lock` and records the integrity hash and size of every Kind
// in the pinned groups.
package lockfile

import (
	"errors"
	"fmt"
	"os"

	goyaml "github.com/goccy/go-yaml"
)

// ErrMalformedIntent is returned when schemalock.yaml cannot be decoded or
// fails structural validation (e.g. missing version field).
var ErrMalformedIntent = errors.New("malformed schemalock.yaml")

// ErrMalformedLock is returned when schemalock.lock cannot be decoded.
var ErrMalformedLock = errors.New("malformed schemalock.lock")

// ErrMalformedID is returned when a lock entry ID does not follow the
// expected "ecosystem/group@version" format.
var ErrMalformedID = errors.New("malformed lock entry id")

// IntentFile represents schemalock.yaml — the user-authored intent file that
// declares which schema groups to pin.
type IntentFile struct {
	// Version is the schema version of this file. Currently always 1.
	Version int `yaml:"version"`
	// Registry is an optional override for the CDN base URL.
	// Defaults to https://cdn.schemalock.dev when empty.
	Registry string `yaml:"registry,omitempty"`
	// Ecosystems maps ecosystem names (e.g. "kubernetes") to a list of
	// "group@version" specifiers (e.g. "operator.victoriametrics.com@0.70.0").
	Ecosystems map[string][]string `yaml:"ecosystems"`
}

// ReadIntent parses schemalock.yaml from the file at path.
func ReadIntent(path string) (IntentFile, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return IntentFile{}, fmt.Errorf("reading intent file %s: %w", path, err)
	}
	return DecodeIntent(b)
}

// DecodeIntent parses schemalock.yaml from b.
// Returns ErrMalformedIntent if the YAML is invalid or the version field
// is missing/zero.
func DecodeIntent(b []byte) (IntentFile, error) {
	var f IntentFile
	if err := goyaml.Unmarshal(b, &f); err != nil {
		return IntentFile{}, fmt.Errorf("%w: %s", ErrMalformedIntent, err)
	}
	if f.Version == 0 {
		return IntentFile{}, fmt.Errorf("%w: missing or zero version field", ErrMalformedIntent)
	}
	return f, nil
}
